### ISSUE TITLE
JSON-multicall

### ISSUE THREAD

**Issue by HMAZonderland** [gggeek/phpxmlrpc-extras#9]
I was wondering why the JSON multi call feature is not -yet- implemented. Are you planning to support this feature in the near future?

**Comment by HMAZonderland** [comment]
Perhaps this question escaped your attention @gggeek, so here's a bump.

**Comment by gggeek** [comment]
well, 1st of all we should rebase the json lib on xmlrpc lib v4, which is no small feat...

**Comment by HMAZonderland** [comment]
Do you have a roadmap or global planning, maybe I can assist somewhere.

**Comment by gggeek** [comment]
Not really. But if you want to create a new branch and start any work in it, it would be good. I think that the initial big chunk of moving classes to namespaces, changing what they extend etc... should not be hard.

On a side note: in the age of composer it might be worth splitting of the jsonrpc implementation from the rest of the 'extras' package...

**Comment by HMAZonderland** [comment]
Well then you might need to split the phpxmlrpc repository into a separate branch since xml and json are both the format of the data you want to sent. Hoe things are communicated is the same.

**Comment by gggeek** [comment]
ET oila': https://github.com/gggeek/phpxmlrpc-jsonrpc

**Comment by HMAZonderland** [comment]
Nice!

**Comment by gggeek** [comment]
I also started creating a 'core' package which will be the one containing Interface definition as well as most of the code dealing with stuff such as HTTP and charsets: https://github.com/gggeek/phpxmlrpc-http

**Comment by gggeek** [comment]
After long time, work has finally picked up on implementing phpxmlrpc-jsonrpc on top of phpxmlrpc v4.5.

At the moment work on the 'new major version' of phpxmlrpc, which includes the split in http,rpc,charset,protocol components is suspended.

Closing this bug in favour of https://github.com/gggeek/phpxmlrpc-jsonrpc/issues/2
